### ISSUE TITLE
Vehicles

### ISSUE THREAD

**Issue by Dominiquini** [raiguard/Factorio-CursorEnhancements#1]
#### Is your feature request related to a problem? Please describe.

When I place a vehicle (car, tank, hovercraft, aircraft) on the ground, the cursor continues with the ghost of the selected vehicle.

#### Describe the solution you'd like

Do not leave a ghost on the cursor when I place a vehicle on the ground

#### Additional context

---

**Comment by raiguard** [comment]
You can turn this off in the mod settings.

![image](https://user-images.githubusercontent.com/3515394/93036578-84194100-f5fd-11ea-9604-65e412bc9cf4.png)
