### ISSUE TITLE
Feature: Skip unknown entities in the middle, don't break the chain (mods tolerance behaviour)

### ISSUE THREAD

**Issue by saaadel** [raiguard/Factorio-CursorEnhancements#10]
#### Is your feature request related to a problem? Please describe.

If we have a big JSON, and uninstall/disable some mod - the flow is broken, and we need to fix the chain in the configuration JSON (remove missed entities in the middle of a some chain)

#### Describe the solution you'd like

When you parse the JSON - just check if the entity exists? If no - remove it from the chain.
Example:
{ "a": "b", "b": "c" }
if we removed some mod, and it removes "b" entity, then your mod should just skip it in the chain:
{ "a": "c" }

So it won't require us to change this JSON each time we switch between different servers with a different set of mods.

#### Additional context

None.

**Comment by raiguard** [comment]
The custom overrides were removed in 2.0, so this is no longer applicable.
