### ISSUE TITLE
nit: Unnecessary modifier in pattern

### ISSUE THREAD

**Issue by kryojenik** [raiguard/Factorio-CursorEnhancements#11]
https://github.com/raiguard/Factorio-CursorEnhancements/blob/121f0ab4afb0cb306e2a19f104feba673734f8b7/src/control.lua#L37

The pattern "^cen-%-scroll%-(%a*)$"  pedantically should be "^cen%-scroll%-(%a*)$".

It works just fine as is, but it could also accept a non-existant "ce-scroll-next" or "cennnnnnnn-scroll-next", etc...

**Comment by raiguard** [comment]
Thanks, I'm not sure how it's been working up until now. That extra `-` means it is always looking for an extra character there. It's puzzling why that didn't break it.
