### ISSUE TITLE
hope more Related items

### ISSUE THREAD

**Issue by luaotix** [raiguard/Factorio-CursorEnhancements#12]
First of all, I like this mod very much, especially the  function of related items scrolling, which greatly improves my gaming experience.
I installed two mods: Deadlock-belt boxes-loaders and UltimateBelts. They offer more belts and inserters, but this is beyond the scope of Cursor Enhancements. Can you include these items?
Thanks.

**Comment by raiguard** [comment]
You can add your own related item paths in the mod settings. Right now it's in JSON format, but I may consider adding a GUI for it in the future. The related items feature has a lot of potential that is currently untapped.

That said, I will add presets for these two mods.
