### ISSUE TITLE
Put ghost in cursor even when I don't have the item before-hand.

### ISSUE THREAD

**Issue by Layarion** [raiguard/Factorio-CursorEnhancements#13]
Sometimes I see something in the world I want to press Q over to get a ghost cursor of it. Thing is, i have no such item in my inventory at the moment. I'm trying to plan out additional placements of an object, but I first need to pick the item up, place it back down where i got it from, and finally be able to do what I wanted with the ghost object.

Basically I want to hit Q over an object I have zero of in my inventory, and start planting ghost.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/144978141-4e6a3fa1-3219-4244-a96b-692f4ee43234.png)

This is actually a vanilla feature (interface settings).
