### ISSUE TITLE
Force object replacement?

### ISSUE THREAD

**Issue by Layarion** [raiguard/Factorio-CursorEnhancements#14]
I often run into the issue, where I'm trying to copy and paste splitters onto a belt. Thing is, I have to delete the belt before it'll let me do that. Even when holding Shift.

I wish I could do something like hold Shift+Alt and that'll tell the game to delete whatever building is in the way, and make it so.

**Comment by raiguard** [comment]
Sorry, but I can't implement this in a consistent way, because there is no way to tell when you're holding a button in the Factorio API. So it would be very janky.
