### ISSUE TITLE
(suggestion) Shift+Scroll on item Stacks.

### ISSUE THREAD

**Issue by BentoGambin** [raiguard/Factorio-CursorEnhancements#15]
It would be awesome and severely appreciated if you could add the shift+scroll similarly to mouse tweaks:
On opening a container -> (with mouse cursor over an item slot) shift + scroll up will add one more item of the same type to that container. Shift + scroll down will remove one item of the selected item stack from the entity's inventory. 
The main benefit of it would be removing a few items on a output chest without having to be quick in order for the chest to not fill up before you get 5 items and place the stack back.

I hope I was clear enough. Hope you can make it.
Thanks in advance.

**Comment by raiguard** [comment]
I have wanted this for a long time. However, instead of shift+scroll, I want to use the hotkeys for dropping and picking up items (Z and F respectively). That would be mighty cool.

**Comment by raiguard** [comment]
https://user-images.githubusercontent.com/3515394/145517017-2b0e4253-047b-4f8c-aa7b-e52108e9ca2c.mp4

First prototype is done. That was easier than expected!

**Comment by BentoGambin** [comment]
Amazing!

**Comment by raiguard** [comment]
The initial prototype worked, but there are too many edge cases I cannot account for with multi-inventory entities. I cannot tel which slot you're actually hovering over, only which item. So if a recipe has the same item as an input and output, there would be no way to tell where it should go. Additionally, if you use the hotkeys while holding an item, it entirely breaks.

Sorry.
