### ISSUE TITLE
Middle Mouse Button Drag on Wagons and markable slots.

### ISSUE THREAD

**Issue by BentoGambin** [raiguard/Factorio-CursorEnhancements#16]
instead of having to middle click every slot with item on hand, or use shift right click then drag around with shift left click and an auto-clicker, it would be awesome to just be able to hold and drag middle click over the slots with item in hand.
Don't know if it's possible but would be very awesome if you could take a look.
Best regards.

**Comment by raiguard** [comment]
Unfortunately this is straight-up impossible. Sorry. :/

**Comment by BentoGambin** [comment]
Sad. Thanks for taking a look!
