### ISSUE TITLE
Improvements/refactoring of quick-crafting

### ISSUE THREAD

**Issue by azaghal** [raiguard/Factorio-CursorEnhancements#17]
Some time ago I posted about eventual addition of quick-crafting to the mod, and I can see you have added it already (I went on a bit of hiatus for a while, so never got around to submitting a patch).

However, I was wondering if you would be interested in some changes and additions to it. And before I start working on the patch, I just wanted to bounce the idea before committing to it :)

So, most of my impressions and expectations are really based around the [Crafting Tools](https://mods.factorio.com/mod/Kux-CraftingTools) mod, and to a large degree the suggestions will be more about bringing the quick-crafting in Cursor Enhancements in line with is implemented in Crafting Tools.

So, here is a couple of changes I would like to implement:

- Two possible batch sizes for crafting - one and five. Crafting single item can be useful when you want something very specific that is not used very often.
- Batch sizes should correspond to the number of crafting results, not the number of times to invoke the recipe. So, if player requests 5 yellow belts to be crafted, invoke the crafting recipe three times (which would produce 6 belts). This should be closer to player's expectations on how many items they want.
- Make the recipe selection a bit smarter. For example, find all possible recipes, figure out for which one the player has sufficient ingredients, take into account probabilities, take into account whether the player can even use the recipe for hand-crafting.

So, do you have any thoughts on this, and would you be ok with me working on a patch for the above?

P.S.
Sorry for not going for the bug report template, but this is more of a feature request.

**Comment by raiguard** [comment]
Done and dusted.
