### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Yokmp** [raiguard/Factorio-CursorEnhancements#18]
### Description

Some things i came up with recently:
- If i drag a wall over a rail it should place a gate. I kinda expect it because belts do it (with undergroundies at least).
- Also dragging a long line (maybe 4+) of pipes should replace them with underground pipes in a way the smart belt thingy works. Like drag and press R to change direction while also place underground pipes.
- And pressing Q on water gives you a pump.

Great Mod. Should be vanilla.

**Comment by raiguard** [comment]
Q for pump feels like a good feature, but the others feel out of scope for what this mod does.
