### ISSUE TITLE
"Personal registry overrides" behaviour

### ISSUE THREAD

**Issue by Arkane-x6** [raiguard/Factorio-CursorEnhancements#2]
Hi! I override cursor scrolling for some items, like power poles, inserters, with bob's mods.

My idea with that was to have the same behavior with the poles as with the belts ; separate poles types when scrolling :
You have a big electric pole? Scroll for other big electric poles only, etc..

```JSON
{
"big-electric-pole"   :"big-electric-pole-2",
"big-electric-pole-2" :"big-electric-pole-3",
"big-electric-pole-3" :"big-electric-pole-4",

"small-electric-pole"    :"medium-electric-pole",
"medium-electric-pole"   :"medium-electric-pole-2",
"medium-electric-pole-2" :"medium-electric-pole-3",
"medium-electric-pole-3" :"medium-electric-pole-4"
}
```

But with this, when I scroll down with ``big-electric-pole``, I get the ``medium-electric-pole`` (like the previous/normal settings)
*I expect the mod don't change item here*

Another problem with inserters : I scroll up with an *Ultimate inserter*, it give me an *Express stack inserter*
*Same, I expect the mod stop scrolling here*
I tried to set *(something like)* ``"inserter-5":""``, but it doesn't work

I'm doing this wrong?

I don't know, *maybe*, it better to use "arrays in array" structure? Like:
```JSON
[
	[
		"small-electric-pole",
		"medium-electric-pole",
		"medium-electric-pole-2",
		"medium-electric-pole-3",
		"medium-electric-pole-4"
	],
	[
		"big-electric-pole",
		"big-electric-pole-2",
		"big-electric-pole-3",
		"big-electric-pole-4"
	]
]

```

**Comment by raiguard** [comment]
I forgot to mention in the FAQ that you can negate something's next item by doing `"item-name": false`. I'll add that.

But you're right that the format is pretty cumbersome, I'll probably change it. And it will probably be an array in arrays structure, like you suggested.

**Comment by Arkane-x6** [comment]
``false``, I forgot json allows bool values ! xD

So, I added ``"medium-electric-pole-4":false`` and ``"big-electric-pole-4":false``
It seems that does not change anything. (With poles and inserters)
Looks like I don't have always the priority on the cycle 

I'm glad that help you find a *better* format then :)

**Comment by raiguard** [comment]
Hmm, you're right, it doesn't work for the player settings (but it _does_ work if a mod uses the remote interface to do it). I'll fix it for the next version.

**Comment by raiguard** [comment]
Heh... I ended up completely restructuring the code in order to fix this problem. The format for adding overrides is still the same for now, that will change later on once I figure out some other things.

Anyway, fixed for the next version.

**Comment by Arkane-x6** [comment]
Thank you! :+1:
It works fine :)

**Comment by raiguard** [comment]
I'm going to close this because I'm pretty happy with how it works now and changing it would require a complete rewrite. Sorry!
