### ISSUE TITLE
Smart pipette in upgrade planner does not function

### ISSUE THREAD

**Issue by Brickcaster** [raiguard/Factorio-CursorEnhancements#21]
### Description

What happens:
If I use pipette (q) on an item in the upgrade planner, either nothing happens or it pipettes the tile below the window.
![image](https://github.com/raiguard/CursorEnhancements/assets/13324089/dde4267c-acf2-4be1-a23f-4299379681e1)

What I expected:
The entity-prototype is put onto my cursor as if I had done the pipette on something in a blueprint.
![image](https://github.com/raiguard/CursorEnhancements/assets/13324089/40c18dbc-346a-4a85-972b-f00129bfddb5)

**Comment by raiguard** [comment]
This is because the game is not providing `selected_prototype` in the upgrade planner. This is not something I can fix on the mod side.
