### ISSUE TITLE
Item under cursor returns to blank when robot steals last item from inventory

### ISSUE THREAD

**Issue by Lezduit** [raiguard/Factorio-CursorEnhancements#22]
### Description

When holding an item under the cursor and a robot (e.g. from a personal roboport) uses that item to build a blueprint/ghost, the cursor returns to a blank state (nothing selected to place).

I expected the cursor to become a ghost instead.

### Reproduction

1. have personal roboport and robots, disabled (alt+r default)
2. have _n_ items of placeable entity (first encountered using pipes, confirmed with other entities as well)
3. place _n+1_ **ghost** entities
4. activate roboport
5. watch pointer turn blank
6. become frustrated

also occurs when roboport is already active, but this way it is easier to reproduce

**Comment by raiguard** [comment]
I think I originally did this on purpose (the current logic only runs when you actively place or remove something), but with the personal roboport I can see how it would be annoying. Fixing it will incur a slight UPS drain but it should be fine.

**Comment by raiguard** [comment]
Actually, now I remember why I didn't do it this way - there isn't a good way for me to distinguish between "a robot removed the item" and "you placed the item into a chest". The logic I just wrote to fix this will give you a ghost cursor if you put something into a chest. I might be able to fix that by listening for the various inventory management custom-inputs, but that would have other edge cases.

Unfortunately, this will have to be a wontfix. Sorry!
