### ISSUE TITLE
Add setting to disable tile selection, or more specifically exclude dectorio ground tiles

### ISSUE THREAD

**Issue by HyperEpsilon** [raiguard/Factorio-CursorEnhancements#23]
So, I have [Dectorio](https://mods.factorio.com/mod/Dectorio) installed and keep pressing Q over things and accidentally putting the `landscaping-tile` for the ground I'm hovering over in my cursor. I often try and clear my cursor by pressing Q a few times over ground, but because of Dectorio that ground is now a valid tile to place.

Would it be possible to either add a setting to disable all tile selection (I like the other quick select features) and/or add a setting to disable selection of anything with the dectorio landscaping subgroup?

**Comment by raiguard** [comment]
I thought about adding this, but this problem could be easily avoided if you just press Q one time instead of spamming it.
