### ISSUE TITLE
mod load error when loading with both pyae and editor extensions in 2.0

### ISSUE THREAD

**Issue by WarlordFTW** [raiguard/Factorio-CursorEnhancements#27]
### Description

![image](https://github.com/user-attachments/assets/ad14f6f2-7bfd-4887-adea-c9133b54fe44)
[factorio-current.log](https://github.com/user-attachments/files/17464760/factorio-current.log)

I got the same error with py and ee. reported to them and they fixed something on their end which fixed this

### Reproduction

attached my mod-list for easy reproduction
[mod-list.json](https://github.com/user-attachments/files/17464772/mod-list.json)

**Comment by raiguard** [comment]
This has nothing to do with cursor enhancements.
