### ISSUE TITLE
Cursor not replaced with ghost item when bots remove items from your inventory

### ISSUE THREAD

**Issue by DarkShadow44** [raiguard/Factorio-CursorEnhancements#29]
### Description

I often place ghosts wile having personal robots, when my items run out my cursor doesn't switch to the ghost item.
It works when I manually place the items, but not when the robots take them.

### Reproduction

1. Have personal robots active
2. Have two radars in inventory
3. Place two radar ghosts with shift-leftclick
4. The bots will take your radars and leave the cursor empty

(Mod version 2.2.0, Factorio 2.0.10)

**Comment by raiguard** [comment]
This is intentional. There is no way to reliably disambiguate between "robot took item out of my inventory" and "player ctrl+clicked the item into a chest" and it was causing problems. Auto-ghost-cursor only happens when you manually place entities.

**Comment by DarkShadow44** [comment]
Aw, too bad. It's one of my biggest issues, wouldn't it be possible to have an option for that?
