### ISSUE TITLE
Crash when loading saved game

### ISSUE THREAD

**Issue by Dominiquini** [raiguard/Factorio-CursorEnhancements#3]
#### Describe the Bug
Crash when I try to load my saved game

#### To Reproduce
Install "Cursor Enhancements v1.0.2" And "Editor Extensions v1.5.19"
The crash occurs when I try to load my saved game
This error not happen when I have "Editor Extensions v1.5.19" and "Cursor Enhancements v1.0.1" 

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username
Username: Dominiquini
Save file:
[Barba.zip](https://github.com/raiguard/Factorio-CursorEnhancements/files/5240016/Barba.zip)

#### Log file
Log file: 
[factorio-previous.log](https://github.com/raiguard/Factorio-CursorEnhancements/files/5240276/factorio-previous.log)

Screenshot: 
![factorio_vwB0Jt30bi](https://user-images.githubusercontent.com/1180808/93489604-3f402380-f8f7-11ea-88b7-0a035579b22a.jpg)

**Comment by raiguard** [comment]
Thanks for the report. This is actually in issue with Editor Extensions itself, not Cursor Enhancements (confirmed by the fact that the screenshot says EE errored instead of CE). I will release a patch to EE shortly to address this issue.

**Comment by raiguard** [comment]
The patch for EE has been released.
