### ISSUE TITLE
"Recall last item" overrides "clear cursor" when cursor has a selection tool.

### ISSUE THREAD

**Issue by NotRexButCaesar** [raiguard/Factorio-CursorEnhancements#31]
### Description

When "recall last item" and "clear cursor" are bound to the same key, it is not possible to clear the cursor when holding a selection tool.  I am not sure whether you can do anything about this.

### Reproduction

Bind both things to "shift + enter" and then unbind anything else which had been bound to "shift + enter".
Hold a deconstruction planner in the cursor.
Press shift and enter, the cursor will not be cleared.  If "recall last item" is unbound, shift enter will now clear the cursor.

**Comment by raiguard** [comment]
It doesn't work for me at all when I bind them to the same key.

I'm going to say "don't do that". :)
