### ISSUE TITLE
QuickCraft Not Working

### ISSUE THREAD

**Issue by Quest79** [raiguard/Factorio-CursorEnhancements#32]
### Description

v 2.2.1

I hover mouse over item that I do have the mats to make. I click my keybind that i have verified and isnt shared elsewhere. It wont work. Ive been using this for weeks and this version stopped it from functioning.

**Comment by Xampa5** [comment]
Doing Ctrl+Q when having your mouse over an item does not work anymore (such has having your mouse over a quickbar slot), you now need to press Q (to grab the ghost in hand) _then_ Ctrl+Q so that it works.

**Comment by raiguard** [comment]
This was an intentional change to fix #28. But it seems like people relied on the old behavior, so I will take a different approach.

**Comment by benvanik** [comment]
Ah this tripped me up too - didn't realize how much I used it!
