### ISSUE TITLE
[Minor issue]

### ISSUE THREAD

**Issue by xeonight** [raiguard/Factorio-CursorEnhancements#35]
### Description

As of Factorio version 2.0.18, ALT-Scroll is now used for scrolling through Quality, so trying to cycle quality with this mod causes items on your mouse to change also.

Ref: https://forums.factorio.com/viewtopic.php?f=3&t=121457

Temporary fix: Change this mod's item scrolling keybinds to CONTROL-ALT-Scroll (or something else), but this is a manual step after discovering the issue.

### Reproduction

install/update to at least 2.0.18 with this mod installed, and then get a ghost item on the cursor, then hold alt and scroll, both quality and the item will change.

**Comment by raiguard** [comment]
I have already changed it to shift+alt+scroll but haven't made a release yet. Thanks for letting me know. :+1:
