### ISSUE TITLE
[Feature Request] Disable cen-auto-ghost-cursor for vehicles

### ISSUE THREAD

**Issue by folknor** [raiguard/Factorio-CursorEnhancements#36]
### Description

Hi. Someone reported a bug with my addon Just Go! that after it placed them into a vehicle several other blueprinted vehicles would be placed alongside it.

I looked over their addons and instantly saw that this mod is probably the cause of the confusion.

And it is :-D

See here: https://mods.factorio.com/mod/folk-justgo/discussion/671eba304d9c012197f0bb91

### Reproduction

Could you possibly disable this by default for vehicles like type=car|locomotive?
Or, alternatively, add a setting to disable it for vehicles, probably disabled by default is sensible?

These types of entities were not blueprintable pre-2.0, but they are now.

**Comment by raiguard** [comment]
I added an exception that will disable it for vehicles when your mod is installed.

**Comment by folknor** [comment]
Thank you!
