### ISSUE TITLE
[Feature request] Make liquids pipettable

### ISSUE THREAD

**Issue by jigsaw3xD** [raiguard/Factorio-CursorEnhancements#38]
### Description

Rn you can only pipette liquids from the combinator menu 
![i69vaw3Enp](https://github.com/user-attachments/assets/c2d4877a-9a1e-4115-a022-bfe2c08be524)

but not from these GUIs (or any other honestly)
![tKYCYf9dlR](https://github.com/user-attachments/assets/6cb6ad5b-8d9b-48f4-b483-8c5c5cd22b99) ![81dr4KqLVb](https://github.com/user-attachments/assets/16ef8970-34ed-4117-9029-c85cb79e3e54)

**Comment by raiguard** [comment]
CE no longer has any smart pipette features, as its feature set has been incorporated into vanilla. Please request this on the Factorio forums.

I removed the references to smarter pipette in the mod description.
