### ISSUE TITLE
Dragging power poles or underground pipes places ghosts

### ISSUE THREAD

**Issue by Choumiko** [raiguard/Factorio-CursorEnhancements#5]
#### Describe the Bug

When dragging poles (small or medium, large ones seem to work) or underground pipes after it placed 1 or 2 entities it switches to placing ghost even though i still have enough items.

Related:
Placing a line of belts makes the ghost icon appear for a few ticks before the next belt is placed, 
video: https://discord.com/channels/139677590393716737/306402592265732098/781081318351175730

#### To Reproduce

1. Load the save
2. Start dragging poles/pipes belts to see ghosts get placed
3. Start dragging belts/lamps to see the ghost icon flicker on your cursor

#### Save file & Username
Choumiko
[cursor_enhancements_bugs.zip](https://github.com/raiguard/Factorio-CursorEnhancements/files/5599132/cursor_enhancements_bugs.zip)

**Comment by raiguard** [comment]
Thanks for the report, fixed for the next release.
