### ISSUE TITLE
Tile pipette works over Interfaces.

### ISSUE THREAD

**Issue by DerFailer36** [raiguard/Factorio-CursorEnhancements#8]
I'm not sure how to best word this, but i hope you get my point.

1. Place some build able tiles
2. Open a interface (inventory/blueprint library/etc.)
3. Move cursor somewhere in the interface with the tiles in the back.
4. Press "Q" (or where ever you bind the pipette tool)
Result: The tile is now on the cursor.
Expected result: Nothings happens.

**Comment by raiguard** [comment]
There actually isn't anything I can do about this. Sorry.
